Repository ServiceNow/AU-Harness, pull requests merged in 2025-09, with the labels that each got.

#2 [DOCS] fix for better compatibility with license scanner
  LICENSE
Labels: documentation

#5 [DOCS + FIX] Spider setup docs & required dependency fix
  README.md
  requirements.txt
  tasks/spoken_language_reasoning/README.md
Labels: bug, documentation

#10 [CHORE] Metric Standardization from 0 to 100 for all tasks
  metrics/README.md
  metrics/bertscore.py
  metrics/bfcl_metric.py
  metrics/bleu_metrics.py
  metrics/comet_score.py
  metrics/diarization_metrics.py
  metrics/llm_judge.py
  metrics/meteor_score.py
  metrics/sql_score.py
  metrics/voice_bench_ifeval_score.py
  metrics/word_error_rate_metrics.py
  tasks/spoken_language_reasoning/bfcl/base.yaml
  tasks/spoken_language_understanding/translation/covost2/base.yaml
Labels: documentation, enhancement
